package cli

import (
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"text/tabwriter"

	"github.com/spf13/cobra"

	"github.com/brumbelow/layerleak/v3/internal/detectors"
)

// newDetectorsCmd groups the read-only catalog commands. There is no way to
// add or change rules from the command line by design (see CONTRIBUTING.md on
// bounded adversarial parsing); the catalog is for transparency.
func newDetectorsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "detectors",
		Short: "Inspect the built-in detector catalog",
	}
	cmd.AddCommand(newDetectorsListCmd())
	return cmd
}

// detectorCatalog is the JSON document `detectors list --format json` prints.
type detectorCatalog struct {
	Count     int              `json:"count"`
	Detectors []detectors.Info `json:"detectors"`
}

func newDetectorsListCmd() *cobra.Command {
	var format string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List every detector id with its confidence tier, strategy and description",
		Long: "List the detector identifiers findings can carry in detector_name, with the confidence tier a match " +
			"carries before path and key context adjust it, the matching strategy and a one-line description. " +
			"docs/detectors.md is generated from the same data.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			infos := detectors.Default().Describe()
			switch strings.ToLower(strings.TrimSpace(format)) {
			case "table":
				return renderDetectorsTable(cmd.OutOrStdout(), infos)
			case "json":
				encoder := json.NewEncoder(cmd.OutOrStdout())
				encoder.SetIndent("", "  ")
				return encoder.Encode(detectorCatalog{Count: len(infos), Detectors: infos})
			default:
				return exitError{code: exitCodeFailure, message: fmt.Sprintf("unsupported output format %q: use table or json", format)}
			}
		},
	}
	cmd.Flags().StringVar(&format, "format", "table", "Output format: table or json")
	return cmd
}

// renderDetectorsTable prints the catalog as an aligned table. Every cell is
// built from compiled-in metadata, so no sanitising is needed.
func renderDetectorsTable(output io.Writer, infos []detectors.Info) error {
	writer := tabwriter.NewWriter(output, 0, 0, 2, ' ', 0)
	if _, err := fmt.Fprintln(writer, "ID\tCONFIDENCE\tSTRATEGY\tDESCRIPTION"); err != nil {
		return err
	}
	for _, info := range infos {
		if _, err := fmt.Fprintf(writer, "%s\t%s\t%s\t%s\n", info.ID, info.Confidence, strings.Join(info.Strategies, ","), info.Description); err != nil {
			return err
		}
	}
	return writer.Flush()
}

// detectorsDocHeader opens docs/detectors.md. The file is regenerated by
// `go test ./internal/cli -run TestDetectorsDocMatchesCatalog -update-docs`
// and TestDetectorsDocMatchesCatalog fails when the catalog changed without it.
const detectorsDocHeader = `# Detector catalog

<!-- Generated from the detector catalog by
     go test ./internal/cli -run TestDetectorsDocMatchesCatalog -update-docs
     Do not edit by hand; the test fails when this file and the catalog disagree. -->

This is the list of identifiers a finding can carry in ` + "`detector_name`" + `
(and SARIF ` + "`ruleId`" + `), as printed by ` + "`layerleak detectors list`" + ` and returned by
` + "`GET /api/v1/detectors`" + `. ` + "`layerleak detectors list --format json`" + ` prints the same
rows as JSON.

**Confidence** is the tier a match carries before path and key context adjust
it: a value under a test or example path can be lowered, one assigned to a
secret-looking key can be raised, and placeholder values are suppressed
rather than reported (see [false-positives.md](false-positives.md)).
` + "`--fail-on`" + ` compares against the adjusted tier. When several strategies or
branches emit the same identifier at different tiers the tiers are joined low
to high (` + "`medium/high`" + `).

**Strategy** names how the identifier is matched:

`

// renderDetectorsMarkdown writes docs/detectors.md from the catalog.
func renderDetectorsMarkdown(output io.Writer, infos []detectors.Info) error {
	var builder strings.Builder
	builder.WriteString(detectorsDocHeader)
	builder.WriteString("| Strategy | Meaning |\n| --- | --- |\n")
	for _, strategy := range detectors.StrategyNames {
		fmt.Fprintf(&builder, "| `%s` | %s |\n", strategy.Name, strategy.Explanation)
	}
	fmt.Fprintf(&builder, "\n## Detectors (%d)\n\n", len(infos))
	builder.WriteString("| Detector | Confidence | Strategy | Description |\n| --- | --- | --- | --- |\n")
	for _, info := range infos {
		strategies := make([]string, 0, len(info.Strategies))
		for _, strategy := range info.Strategies {
			strategies = append(strategies, "`"+strategy+"`")
		}
		fmt.Fprintf(&builder, "| `%s` | %s | %s | %s |\n", info.ID, info.Confidence, strings.Join(strategies, ", "), markdownCell(info.Description))
	}
	_, err := io.WriteString(output, builder.String())
	return err
}

// markdownCell escapes the one character that would break a table row.
func markdownCell(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}
