package cli

// The detector catalog document is generated only by the golden test in
// detectors_cmd_test.go, so its renderer lives with the tests rather than in
// the shipped binary.

import (
	"fmt"
	"io"
	"strings"

	"github.com/brumbelow/layerleak/v3/internal/detectors"
)

// detectorsDocHeader opens docs/detectors.md. The file is regenerated by
// `go test ./internal/cli -run TestDetectorsDocMatchesCatalog -update-docs`
// and TestDetectorsDocMatchesCatalog fails when the catalog changed without it.
const detectorsDocHeader = `# Detector catalog

<!-- Generated from the detector catalog by
     go test ./internal/cli -run TestDetectorsDocMatchesCatalog -update-docs
     Do not edit by hand; the test fails when this file and the catalog disagree. -->

This is the list of identifiers a finding can carry in ` + "`detector_name`" + `
(and SARIF ` + "`ruleId`" + `), as printed by ` + "`layerleak detectors list`" + ` and emitted as
SARIF ` + "`tool.driver.rules`" + ` by ` + "`--format sarif`" + `. ` + "`layerleak detectors list --format json`" + `
prints the same rows as JSON.

**Confidence** is the tier a match carries before path and key context adjust
it: a value under a test or example path can be lowered, one assigned to a
secret-looking key can be raised, and placeholder values are suppressed
rather than reported (see [false-positives.md](false-positives.md)).
` + "`--fail-on`" + ` compares against the adjusted tier. When several strategies or
branches emit the same identifier at different tiers the tiers are joined low
to high (` + "`medium/high`" + `).

**Strategy** names how the identifier is matched:

`

// renderDetectorsMarkdown writes docs/detectors.md from the catalog.
func renderDetectorsMarkdown(output io.Writer, infos []detectors.Info) error {
	var builder strings.Builder
	builder.WriteString(detectorsDocHeader)
	builder.WriteString("| Strategy | Meaning |\n| --- | --- |\n")
	for _, strategy := range detectors.StrategyNames {
		fmt.Fprintf(&builder, "| `%s` | %s |\n", strategy.Name, strategy.Explanation)
	}
	fmt.Fprintf(&builder, "\n## Detectors (%d)\n\n", len(infos))
	builder.WriteString("| Detector | Confidence | Strategy | Description |\n| --- | --- | --- | --- |\n")
	for _, info := range infos {
		strategies := make([]string, 0, len(info.Strategies))
		for _, strategy := range info.Strategies {
			strategies = append(strategies, "`"+strategy+"`")
		}
		fmt.Fprintf(&builder, "| `%s` | %s | %s | %s |\n", info.ID, info.Confidence, strings.Join(strategies, ", "), markdownCell(info.Description))
	}
	_, err := io.WriteString(output, builder.String())
	return err
}

// markdownCell escapes the one character that would break a table row.
func markdownCell(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}
